# Generated by Django 4.0.3 on 2022-06-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter full name', max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=300)),
                ('avater', models.CharField(max_length=100)),
                ('social_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This is the title of blog', max_length=220)),
                ('content', models.TextField(help_text='Write the content of this blog', max_length=2000)),
                ('tag', models.CharField(help_text='Enter the blog keyword', max_length=40)),
                ('image', models.CharField(help_text='Upload a image for this blog', max_length=100)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.CharField(blank=True, choices=[('l', 'Live'), ('d', 'Draft')], default='d', max_length=10)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('short_description', models.CharField(help_text='Enter one or two line about blog', max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Leave your valuable comment', max_length=300)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.blog')),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(help_text='Select a category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
