# Generated by Django 4.0.3 on 2022-07-23 07:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_profile_fullname_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Write the content of this blog', max_length=2000),
        ),
    ]
