# Generated by Django 4.0.3 on 2022-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(help_text='Enter title of your comment', max_length=220, null=True),
        ),
    ]
