# Generated by Django 4.0.3 on 2022-08-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=55, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
